inherit_from: ../.rubocop.yml

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/DocumentationMethod:
  Description: "Document methods."
  Enabled: false

Metrics/MethodLength:
  Description: "Avoid really long methods."
  Enabled: true

Lint/UselessAssignment:
  Description: "Avoid useless assignments."
  Enabled: true
  
Style/FrozenStringLiteralComment:
  Enabled: false

  Layout/LineLength:
  Details: >-
    If lines are too short, text becomes hard to read because you must
    constantly jump from one line to the next while reading. If lines are too
    long, the line jumping becomes too hard because you "lose the line" while
    going back to the start of the next line. 80 characters is a good
    compromise.

  Style/EndOfLine:
  EnforcedStyle: lf 

Security/Eval:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Style/Encoding:
  Enabled: true

Lint:
  Enabled: true

Layout/LineLength:
  Max: 99

AllCops:
  Include:
    - foo.unusual_extension
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'bin/{rails,rake}'
rule_name:
    Description: "description of rule"
    Enabled: true or false
    Key: Value
PreCommit:
  RuboCop:
    enabled: true

  Layout/ClassStructure:
   Categories:
     association:
       - has_many
       - has_one
     attribute_macros:
       - attr_accessor
       - attr_reader
       - attr_writer
     macros:
       - validates
       - validate
     module_inclusion:
       - include
       - prepend
       - extend

